version: '3.8'

services:
  gemini-search-web:
    build: .
    ports:
      - "13010:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - .:/app
      - /app/node_modules